In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [35]:
main = pd.read_csv('C:/Users/WoojaeYang/Desktop/DCR/data/MAIN.csv')
main.head(10)

,SN_KEY,SEER_GRP,AGE,FDX,INDEX_Y,INDEX_MDY,STATIN,DTH,DREGDATE,INDEX_AGE,...,DYS,RTX,SUR,EXMD_BZ_YYYY,G1E_BP_SYS,G1E_BP_DIA,G1E_TOT_CHOL,G1E_LDL,DTH_MDY,TIME
0,a3,2,39,2012-09-15,2017,2017-09-15,1,0,NaN,44,...,1,0,1,2017,113,70,170,69,18992,1567.75
1,a6,9,78,2012-12-19,2017,2017-12-19,0,1,2019-02-03,83,...,0,1,1,2016,145,70,175,104,17930,410.75
2,a8,2,59,2012-05-12,2017,2017-05-12,1,0,NaN,64,...,1,0,1,2016,118,65,176,110,18992,1693.75
3,a11,7,53,2012-12-28,2017,2017-12-28,0,1,2019-05-05,58,...,0,1,0,2017,110,88,183,102,18021,492.75
4,a14,2,70,2012-12-28,2017,2017-12-28,1,0,NaN,75,...,1,0,1,2016,110,70,176,95,18992,1463.75
5,a15,1,60,2012-08-11,2017,2017-08-11,1,1,2017-09-12,65,...,1,1,1,2017,143,67,183,92,17421,31.75
6,a17,2,51,2012-05-07,2017,2017-05-07,1,0,NaN,56,...,1,0,1,2017,116,66,199,100,18992,1698.75
7,a18,1,51,2012-12-28,2017,2017-12-28,1,0,NaN,56,...,1,0,1,2017,134,74,234,167,18992,1463.75
8,a19,1,50,2012-08-04,2017,2017-08-04,0,1,2018-11-08,55,...,1,1,1,2016,136,88,269,166,17843,460.75
9,a21,2,68,2012-08-11,2017,2017-08-11,0,1,2018-05-30,73,...,0,1,1,2016,124,75,228,139,17681,291.75

In [6]:
main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SN_KEY              241 non-null    object
 1   SEER_GRP            241 non-null    int64
 2   AGE                 241 non-null    int64
 3   FDX                 241 non-null    object
 4   INDEX_Y             241 non-null    int64
 5   INDEX_MDY           241 non-null    object
 6   STATIN              241 non-null    int64
 7   DTH                 241 non-null    int64
 8   DREGDATE            105 non-null    object
 9   INDEX_AGE           241 non-null    int64
 10  SIDO_CD             131 non-null    float64
 11  CALC_CTRB_VTILE_FD  131 non-null    float64
 12  DYS                 241 non-null    int64
 13  RTX                 241 non-null    int64
 14  SUR                 241 non-null    int64
 15  EXMD_BZ_YYYY        241 non-null    int64
 16  G1E_BP_SYS          241 non-null    int64
 17  G1E_BP_DIA          241 non-null    int64
 18  G1E_TOT_CHOL        241 non-null    int64
 19  G1E_LDL             241 non-null    int64
 20  DTH_MDY             241 non-null    int64
 21  TIME                241 non-null    float64
dtypes: float64(3), int64(15), object(4)
memory usage: 41.6+ KB

In [11]:
# 2. y 값 설정
y = main['DTH']

# 3. 피처 선택 (결측치 많거나 object 제외)
X = main[['STATIN', 'SUR', 'TIME', 'AGE']]

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   STATIN  241 non-null    int64
 1   SUR     241 non-null    int64
 2   TIME    241 non-null    float64
 3   AGE     241 non-null    int64
dtypes: float64(1), int64(3)
memory usage: 7.7 KB

In [15]:
X.describe()

           STATIN         SUR         TIME         AGE
count  241.000000  241.000000   241.000000  241.000000
mean     0.278008    0.684647  1201.870332   57.601660
std      0.448950    0.465623   564.060929   11.817318
min      0.000000    0.000000    31.750000   32.000000
25%      0.000000    0.000000   644.750000   49.000000
50%      0.000000    1.000000  1516.750000   56.000000
75%      1.000000    1.000000  1663.750000   66.000000
max      1.000000    1.000000  1819.750000   91.000000

In [33]:
logistic = LogisticRegression()
linear = LinearRegression()
scaler = StandardScaler()

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [21]:
logistic_result = logistic.fit(X_train, y_train)
linear_result = linear.fit(X_train, y_train)

C:\Users\WoojaeYang\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [23]:
logistic_result.predict(X_test)

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1], dtype=int64)

In [25]:
linear_result.predict(X_test)

array([ 6.15761759e-02, -9.39219329e-03,  1.12275702e+00,  1.57174631e-01,
        2.74939213e-02,  1.39139932e-01,  7.24400699e-02,  3.41705064e-02,
        1.19674649e+00,  1.04697649e+00,  1.89903778e-01, -4.40237245e-02,
        1.12586864e+00,  9.93716803e-02,  2.03651659e-01,  8.38617869e-01,
        5.04385793e-01,  1.89350586e-01,  8.12485232e-02,  7.09773181e-01,
        5.59961796e-01,  1.15309533e+00,  5.35047507e-02,  1.23019642e+00,
       -4.80513562e-02,  1.42075830e+00,  5.54835087e-04,  1.12393862e+00,
        8.25250602e-01, -7.45740236e-03,  1.19982862e+00,  2.12430423e-02,
        1.11572909e+00,  9.56229007e-01,  8.44754503e-01,  7.61029181e-01,
        1.77600168e-01,  3.52340416e-01,  1.42537305e-01, -3.11392864e-02,
        1.09469345e+00,  9.30642034e-01,  1.43975171e-01, -7.70109865e-02,
       -7.18559554e-02,  8.93533911e-01,  6.47652077e-01,  1.11546557e+00,
        6.77842955e-01])

In [27]:
logistic_result.score(X_test, y_test)

0.9795918367346939

In [29]:
# 간단 계수 확인

coef_df = pd.DataFrame({
    'Variable': X.columns,
    'Coefficient': logistic_result.coef_[0]
})
print(coef_df)

  Variable  Coefficient
0   STATIN    -0.210329
1      SUR     0.630638
2     TIME    -0.018264
3      AGE     0.031077

In [31]:
# 회귀 요약
import statsmodels
import statsmodels.api as sm

# 상수항 추가 (bias term)
X2 = sm.add_constant(X)

# 로지스틱 회귀 모델 적합
logit_model = sm.Logit(y, X2)
logit_result = logit_model.fit()

# 결과 요약 출력
print(logit_result.summary())

Optimization terminated successfully.
         Current function value: 0.079967
         Iterations 11
                           Logit Regression Results
==============================================================================
Dep. Variable:                    DTH   No. Observations:                  241
Model:                          Logit   Df Residuals:                      236
Method:                           MLE   Df Model:                            4
Date:                Fri, 22 Aug 2025   Pseudo R-squ.:                  0.8832
Time:                        10:28:24   Log-Likelihood:                -19.272
converged:                       True   LL-Null:                       -165.05
Covariance Type:            nonrobust   LLR p-value:                 7.186e-62
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         24.1463      6.732      3.587      0.000      10.953      37.340
STATIN        -1.0177      0.953     -1.068      0.285      -2.885       0.850
SUR            2.6447      1.708      1.548      0.122      -0.703       5.992
TIME          -0.0196      0.005     -4.171      0.000      -0.029      -0.010
AGE            0.0306      0.032      0.968      0.333      -0.031       0.093
==============================================================================

Possibly complete quasi-separation: A fraction 0.34 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.

In [74]:
print(dir(statsmodels.api))

['BayesGaussMI', 'BinomialBayesMixedGLM', 'ConditionalLogit', 'ConditionalMNLogit', 'ConditionalPoisson', 'Factor', 'GEE', 'GLM', 'GLMGam', 'GLS', 'GLSAR', 'GeneralizedPoisson', 'HurdleCountModel', 'Logit', 'MANOVA', 'MI', 'MICE', 'MICEData', 'MNLogit', 'MixedLM', 'NegativeBinomial', 'NegativeBinomialP', 'NominalGEE', 'OLS', 'OrdinalGEE', 'PCA', 'PHReg', 'Poisson', 'PoissonBayesMixedGLM', 'ProbPlot', 'Probit', 'QuantReg', 'RLM', 'RecursiveLS', 'SurvfuncRight', 'TruncatedLFNegativeBinomialP', 'TruncatedLFPoisson', 'WLS', 'ZeroInflatedGeneralizedPoisson', 'ZeroInflatedNegativeBinomialP', 'ZeroInflatedPoisson', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '__version_info__', 'add_constant', 'categorical', 'cov_struct', 'datasets', 'distributions', 'duration', 'emplike', 'families', 'formula', 'gam', 'genmod', 'graphics', 'iolib', 'load', 'load_pickle', 'multivariate', 'nonparametric', 'qqline', 'qqplot', 'qqplot_2samples', 'regression', 'robust', 'show_versions', 'stats', 'test', 'tools', 'tsa', 'webdoc']

NameError: name 'X2' is not defined

In [22]:
# 5. 정규화 (로지스틱 회귀용)

X_scaled = scaler.fit_transform(X)