In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

In [6]:
file_path = 'C:/Users/WoojaeYang/Desktop/DCR/data/'
main4 = pd.read_csv(f'{file_path}main4.csv')
main4.head()

,SN_KEY,SEER_GRP,AGE,FDX,INDEX_Y,INDEX_MDY,STATIN,DTH,DREGDATE,INDEX_AGE,SIDO_CD,CALC_CTRB_VTILE_FD,DYS,RTX,SUR,DTH_MDY,TIME,SIDO,CALC,AGEGP
0,a3,2,39,2012-09-15,2017,2017-09-15,1,0,NaN,44,44.0,10.0,1,0,1,18992,1568,2.0,2,1
1,a6,9,78,2012-12-19,2017,2017-12-19,0,1,2019-02-03,83,NaN,NaN,0,1,1,17930,411,NaN,2,2
2,a8,2,59,2012-05-12,2017,2017-05-12,1,0,NaN,64,NaN,NaN,1,0,1,18992,1694,NaN,2,1
3,a11,7,53,2012-12-28,2017,2017-12-28,0,1,2019-05-05,58,NaN,NaN,0,1,0,18021,493,NaN,2,1
4,a14,2,70,2012-12-28,2017,2017-12-28,1,0,NaN,75,NaN,NaN,1,0,1,18992,1464,NaN,2,2

In [8]:
main4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SN_KEY              241 non-null    object
 1   SEER_GRP            241 non-null    int64
 2   AGE                 241 non-null    int64
 3   FDX                 241 non-null    object
 4   INDEX_Y             241 non-null    int64
 5   INDEX_MDY           241 non-null    object
 6   STATIN              241 non-null    int64
 7   DTH                 241 non-null    int64
 8   DREGDATE            105 non-null    object
 9   INDEX_AGE           241 non-null    int64
 10  SIDO_CD             131 non-null    float64
 11  CALC_CTRB_VTILE_FD  131 non-null    float64
 12  DYS                 241 non-null    int64
 13  RTX                 241 non-null    int64
 14  SUR                 241 non-null    int64
 15  DTH_MDY             241 non-null    int64
 16  TIME                241 non-null    int64
 17  SIDO                131 non-null    float64
 18  CALC                241 non-null    int64
 19  AGEGP               241 non-null    int64
dtypes: float64(3), int64(13), object(4)
memory usage: 37.8+ KB

In [24]:
main4['SEER_GRP'].unique()

array([2, 9, 7, 1], dtype=int64)

In [26]:
main4.describe()

,SEER_GRP,AGE,INDEX_Y,STATIN,DTH,INDEX_AGE,SIDO_CD,CALC_CTRB_VTILE_FD,DYS,RTX,SUR,DTH_MDY,TIME,SIDO,CALC,AGEGP
count,241.000000,241.000000,241.0,241.000000,241.000000,241.000000,131.000000,131.000000,241.000000,241.000000,241.000000,241.000000,241.000000,131.000000,241.000000,241.000000
mean,3.091286,57.601660,2017.0,0.278008,0.435685,62.601660,32.687023,6.129771,0.278008,0.394191,0.684647,18564.692946,1202.120332,1.748092,1.775934,1.369295
std,3.221019,11.817318,0.0,0.448950,0.496878,11.817318,13.970344,3.216297,0.448950,0.489693,0.465623,551.403668,564.060929,0.435775,0.417834,0.483618
min,1.000000,32.000000,2017.0,0.000000,0.000000,37.000000,11.000000,0.000000,0.000000,0.000000,0.000000,17421.000000,32.000000,1.000000,1.000000,1.000000
25%,1.000000,49.000000,2017.0,0.000000,0.000000,54.000000,18.500000,3.000000,0.000000,0.000000,0.000000,18021.000000,645.000000,1.500000,2.000000,1.000000
50%,1.000000,56.000000,2017.0,0.000000,0.000000,61.000000,41.000000,6.000000,0.000000,0.000000,1.000000,18992.000000,1517.000000,2.000000,2.000000,1.000000
75%,2.000000,66.000000,2017.0,1.000000,1.000000,71.000000,44.000000,9.000000,1.000000,1.000000,1.000000,18992.000000,1664.000000,2.000000,2.000000,2.000000
max,9.000000,91.000000,2017.0,1.000000,1.000000,96.000000,48.000000,10.000000,1.000000,1.000000,1.000000,18992.000000,1820.000000,2.000000,2.000000,2.000000

In [30]:
seer2 = main4[main4['SEER_GRP'] == 2]
seer9 = main4[main4['SEER_GRP'] == 9]
seer7 = main4[main4['SEER_GRP'] == 7]
seer1 = main4[main4['SEER_GRP'] == 1]

In [32]:
grp2 = seer2['TIME']
grp9 = seer9['TIME']
grp7 = seer7['TIME']
grp1 = seer1['TIME']

In [38]:
f_stat, p_val = stats.f_oneway(grp2, grp9, grp7, grp1)
print(f'F_val= {f_stat:.4f}, P-val= {p_val:.4f}' )

F_val= 2.0432, P-val= 0.1085